name: Deploy

on:
  push:
    branches: [ main ]
  #schedule:
  #  - cron: '00 14 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: s-weigand/setup-conda@v1
        
      - run: conda env update --file environment.yml  --prune
      
      - run: jupyter nbconvert --to html --execute at-summary.ipynb
      
      - run: |
          mkdir ./_build
          mv at-summary.html ./_build/index.html
      
      # Push the notebook's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
